import type { Metadata } from "next";
import { Source_Sans_3 } from "next/font/google";
import "@/lib/styles/globals.scss";
import Header from "@/app/header";
import Footer from "@/app/footer";
import styles from "./packagesPage.module.scss";

const mainFont = Source_Sans_3({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Prague morning jobs",
	description: "Generated by create next app",
};

export default function PackagesLayout({ children }: { children: React.ReactNode }) {
	return (
		<>
			<Header
				extraBottomHeader='Simple pricing. No surprise fees. Advanced features.'
				topHeaderTitle=''
				bottomHeaderTitle='Packages and Subscriptions'
			/>
			{children}
		</>
	);
}
